GET http://localhost:3000

###
GET http://localhost:3000/api/blog/1

###
POST  http://localhost:3000/api/blog
Content-Type: application/json

{
	"title": "yeasayer",
	"text": "this is longevity at it's finest"
}

###
PUT http://localhost:3000/api/blog/1
Content-Type: application/json

{
	"title": "My blog post",
	"text": "Shoot is my second blog post",
}

###
DELETE  http://localhost:3000/api/blog/3

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"username": "rainbow",
    "password": "surprise"
}

###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
	"username": "rainbow",
	"password1": "surprise",
	"password2": "surprise"
}

###
POST http://localhost:3000/api/users/logout

###
GET http://localhost:3000/api/users

###

###

GET http://localhost:3000/dashboard

###
GET http://localhost:3000/api/comments

###
POST  http://localhost:3000/api/blog/1/comment
Content-Type: application/json

{
	"comment": "this is a comment"
}

###
PUT http://localhost:3000/api/comments/1
Content-Type: application/json
# doesn't work yet
{
	"user_id": 6
}

###
DELETE http://localhost:3000/api/comments/1