GET http://localhost:3000

###

GET http://localhost:3000/api/blog/1

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"username": "rainbow",
    "password": "surprise"
}

###

POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
	"username": "rainbow",
	"password1": "surprise",
	"password2": "surprise"
}

###

GET http://localhost:3000/api/users


PUT http://localhost:3000/updateBlog/1
Content-Type: application/json

{
	"title": "My blog post",
	"content": "This is my second blog post"
}

###

DELETE http://localhost:3000/deleteBlog/1

###

GET http://localhost:3000/sessions